### ISSUE TITLE
the .gitignore file seems wrong

### ISSUE THREAD

**Issue by mwarger** [jihchi/app-template-rescript-react#4]
After running the template command, the gitignore I see is this:
```
.build
build
web_modules
node_modules
```

It seems like it should be the one in the root of the project - https://github.com/jihchi/app-template-reason-react/blob/master/.gitignore

It doesn't seem like it's being copied to the template output.

**Comment by jihchi** [comment]
Hi @mwarger , 

Yes, I'm aware of this, It seems like [create-snowpack-app](https://github.com/pikapkg/create-snowpack-app/blob/master/packages/create-snowpack-app/index.js#L93-L96) does not support `.gitignore` from template at the moment.

**Comment by jihchi** [comment]
I've created an issue in https://github.com/pikapkg/create-snowpack-app/issues/164
